# This is the name of your Worker.
name = "kalp-ai-discord-bot"

# This is the most important line.
# It tells Wrangler where your main script is.
# Make sure this path is correct for your project!
main = "index.js"

# This ensures your Worker runs with a recent version of the runtime.
compatibility_date = "2025-07-28"